### ISSUE TITLE
Ctrl-B to sync and run all files

### ISSUE THREAD

**Issue by siliconwitch** [brilliantlabsAR/ar-studio-for-vscode#25]
Should save all files, and then send \x03\x04 to reset (i.e. run main.py)

**Comment by uma-shankar-TE** [comment]
CTRL-B is default vs code shortcut to close or open sidebar .
something different like CTRL + Shift +B

**Comment by siliconwitch** [comment]
Yep, Ctrl-Shit-B works. i.e. the standard build shortcut. Possible to catch it as the build command? In case someone has changed their keybinding for build

**Comment by uma-shankar-TE** [comment]
ok will try to set  keyboard mapping in package.json and also make it as command so that user can map as per choice
