### ISSUE TITLE
Sync on connection

### ISSUE THREAD

**Issue by siliconwitch** [brilliantlabsAR/ar-studio-for-vscode#26]
Ask the user on first connection if they'd like to sync all the files from `device files` to Monocle

**Comment by uma-shankar-TE** [comment]
Sync means uploading all from local to device or from device to local?

**Comment by siliconwitch** [comment]
from local to device

**Comment by siliconwitch** [comment]
Actually I'm wondering of #25 covers this. Maybe it's not needed because the user can just do Ctrl-Shift-B on connection and the same thing happens

**Comment by uma-shankar-TE** [comment]
ctrl+shift+B will be a command. what we can do is check outer level directory if not matched . we can invoke that command automatically

**Comment by siliconwitch** [comment]
Yeah it could accidentally overwrite the user app if they make a new project let's say. Let's start with #25 and see how it feels. If it's okay then we can skip this issue

**Comment by siliconwitch** [comment]
No longer needed since we're adding the other features now
