### ISSUE TITLE
Saving files from arbitrary locations in the workspace. Using `.brilliant/device-files.json`

### ISSUE THREAD

**Issue by siliconwitch** [brilliantlabsAR/ar-studio-for-vscode#31]
.device-files to be generic for Frame of Monocle

**Comment by uma-shankar-TE** [comment]
How decide path on device where to save 
eg. for local it can be `workspace/someDir/SomeOtherDir/test.py` and user may want to save it to `/test/test.py` on device

**Comment by siliconwitch** [comment]
Great question!

Perhaps an option when clicking “upload to device”. Let the user type the path. If they don’t type anything it just saves on the root.

the device files then contains source and destination paths

**Comment by siliconwitch** [comment]
Changed path of `device-files.json` to `.brilliant/`
