### ISSUE TITLE
Build command should automatically save open files

### ISSUE THREAD

**Issue by siliconwitch** [brilliantlabsAR/ar-studio-for-vscode#42]
Had this idea during trying to make different screens. Any ideas if it could cause some problems?

**Comment by uma-shankar-TE** [comment]
When a new screen is created, all files are updated within the .brilliant/device-files.json directory. However, attempting to save all currently open files may result in unintended saving of other files (even after filtering out Python files) that are not meant for the device.

**Comment by uma-shankar-TE** [comment]
Done
