### ISSUE TITLE
Typo in suggestion snippet

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/ar-studio-for-vscode#47]
https://github.com/brilliantlabsAR/ar-studio-for-vscode/blob/main/snippets/display.json#L189

Here, `MIDDLE_CENTER` should be `HEIGHT`

https://discord.com/channels/963222352534048818/1175766091998437537

**Comment by uma-shankar-TE** [comment]
fixed #https://github.com/brilliantlabsAR/ar-studio-for-vscode/commit/d762794a7410468cc220f26e711235fffaba2212
